project_id = "tgmdopzzvhgzzqwdommp"

[functions.process-images]
verify_jwt = false

[functions.analyze-images]
verify_jwt = false

[functions.upscale-images]
verify_jwt = false

[functions.compress-images]
verify_jwt = false