project_id = "tgmdopzzvhgzzqwdommp"

[api]
enabled = true
port = 54321
schemas = ["public", "graphql_public"]
extra_search_path = ["public", "extensions"]
max_rows = 1000

[functions.process-images]
verify_jwt = false

[functions.process-image]
verify_jwt = false

[functions.process-single-image]
verify_jwt = false

[functions.image-processing-worker]
verify_jwt = false

[functions.create-processing-job]
verify_jwt = false

[functions.process-image-step]
verify_jwt = false

[functions.processing-queue]
verify_jwt = false

[functions.cleanup-scheduler]
verify_jwt = false

[functions.analyze-images]
verify_jwt = false

[functions.upscale-images]
verify_jwt = false

[functions.compress-images]
verify_jwt = false

[functions.generate-masks]
verify_jwt = false

[functions.remove-backgrounds]
verify_jwt = false

[functions.composite-images]
verify_jwt = false

[functions.retry-single-image-enhancement]
verify_jwt = false

[functions.render-composite]
verify_jwt = false