// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://tgmdopzzvhgzzqwdommp.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InRnbWRvcHp6dmhnenpxd2RvbW1wIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTgzOTczOTksImV4cCI6MjA3Mzk3MzM5OX0.970mH6w0v5aHukrHmCKrNdj5c7QRf5g3Lo8y5HBnv8A";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});